---
- name: "패키지 삭제"
  hosts: all
  tasks:
  - name: 패키지 삭제 - httpd, mariadb-server, php, mutt
    yum:
      name: "{{ packages }}"
      state: absent
  vars:
    packages:
    - httpd
    - mariadb-server
    - php
    - mutt