---
- name: $HOME/.bashrc 파일 배포
  hosts: all
  gather_facts: no 
  remote_user: devops
  become: false
  tasks:
    - name: 환경 파일 배포 - 
      template: 
        src: templates/bashrc.j2
        dest: .bashrc
        # dest: /home/devops/.bashrc
        # owner: devops
        # group: devops
        # mode: '0644'
    - name: 디렉토리 복사
      copy:
        src: files/blesh
        dest: .local/share
