---
- name: 잡 제어 플레이브 예제
  hosts: webservers
  gather_facts: yes
  vars_files: vars/vars.yml
  tasks:
    # Fail Fast Message
    # ansible localhost -m setup -a 'filter=ansible_memtotal_mb'
    - name: 시스템 사양 점검 - 메모리 & 배포판
      fail:
        msg: "{{ ansible_hostname }}'s Minimun memory: 256MB"
      when: 
        - ansible_memtotal_mb <= 256
        - ansible_distribution != 'CentOS'

    # Install all Packages
    - name: 웹 최신 패키지 설치
      yum:
        name: "{{ packages }}"
        state: latest

    # Enable ans start services
    - name: 웹 서비스 기동
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items: "{{ services }}"

  - name: 블록 - 웹서버 설정이 잘 되면
    block:
    - name: 웹 서버 설정
        # files/index.html -> /var/www/html/index.html
        # files/localhost.key -> /etc/pki/tls/localhost.key
        # files/localhost.crt -> /etc/pki/certs/localhost.crt
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items: "{{ conf_files }}"
        notify: restart httpd
      rescue: 
    - name: 웹 서버 설정 에러 메세지 출력
      debug:
        msg: "웹서버 설정 및 인증서 배포가 에러가 발생했습니다"
  
  
  handlers:
  - name: restart httpd
    service:
      name: httpd
      state: restarted

