---
- name: Task Failure Exercise
  hosts: databases
  gather_facts: no
  vars:
    web_package: httpd     # 잘못된 정보 그대로 입력
    db_package: mariadb-server
    db_service: mariadb
  tasks:
#   ● mariadb 서비스 disable
  - name: Start {{ db_service }} service
    service:
      name: "{{ db_service }}"
      state: absent
  
#   ● httpd 패키지 삭제
  - name: Install {{ db_package }} package
    yum:
      name: "{{ web_package }}"
      state: absent
#   ● mariadb-server 패키지 삭제
  - name: mariadb-server 패키지 삭제
    yum:
      name: "{{ db_package }}"
      state: absent
